- hyperparam_set:
    batch_norm: 'on'
    batch_size: 256
    data_aug_cutout_size: 7
    max_learning_rate: 0.2
    momentum: 0.9
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 512
    data_aug_cutout_size: 7
    max_learning_rate: 0.2
    momentum: 0.9
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 256
    data_aug_cutout_size: 14
    max_learning_rate: 0.2
    momentum: 0.9
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 512
    data_aug_cutout_size: 14
    max_learning_rate: 0.2
    momentum: 0.9
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 256
    data_aug_cutout_size: 7
    max_learning_rate: 0.2
    momentum: 0.99
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 512
    data_aug_cutout_size: 7
    max_learning_rate: 0.2
    momentum: 0.99
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 256
    data_aug_cutout_size: 14
    max_learning_rate: 0.2
    momentum: 0.99
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 512
    data_aug_cutout_size: 14
    max_learning_rate: 0.2
    momentum: 0.99
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 256
    data_aug_cutout_size: 7
    max_learning_rate: 0.6
    momentum: 0.9
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 512
    data_aug_cutout_size: 7
    max_learning_rate: 0.6
    momentum: 0.9
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 256
    data_aug_cutout_size: 14
    max_learning_rate: 0.6
    momentum: 0.9
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 512
    data_aug_cutout_size: 14
    max_learning_rate: 0.6
    momentum: 0.9
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 256
    data_aug_cutout_size: 7
    max_learning_rate: 0.6
    momentum: 0.99
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 512
    data_aug_cutout_size: 7
    max_learning_rate: 0.6
    momentum: 0.99
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 256
    data_aug_cutout_size: 14
    max_learning_rate: 0.6
    momentum: 0.99
- hyperparam_set:
    batch_norm: 'on'
    batch_size: 512
    data_aug_cutout_size: 14
    max_learning_rate: 0.6
    momentum: 0.99
